server:
  port: 8088

spring:
  datasource:
    ##url: "jdbc:mysql://localhost:3310/setting"
    url: "jdbc:mysql://localhost:3306/gitlab-webhook-to-gitHub?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai"
    username: "root"
    password: ""
  jpa:
    generate-ddl: true
    show-sql: true
    properties:
      hibernate:
        dialect: "org.hibernate.dialect.MySQL57Dialect"
    hibernate:
      ddl-auto: "update"

dingTalkUrlPre: https://oapi.dingtalk.com/robot/send

